spring:
  application:
    name: gateway


server:
  port: 44440

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://root:123456@localhost:11110/eureka/

zuul:
#  routes:
#    customer-service: # 这个名字是任意写的，保持唯一就可以
#      path: /customer/**  #配置请求URL的请求规则
#      serviceId: customer #指定Eureka注册中心中的服务id
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket时
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000