spring:
  application:
    name: EurekaServer
  security:
    user:
      name: root
      password: 123456


server:
  port: 44440

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://root:123456@localhost:${server.port}/eureka/
